//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Webserver : global::System.Configuration.ApplicationSettingsBase {
        
        private static Webserver defaultInstance = ((Webserver)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Webserver())));
        
        public static Webserver Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://159.89.100.130:8182/")]
        public string baseURL {
            get {
                return ((string)(this["baseURL"]));
            }
            set {
                this["baseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/v1/")]
        public string apiVersion {
            get {
                return ((string)(this["apiVersion"]));
            }
            set {
                this["apiVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contacts/")]
        public string contactsEndpoint {
            get {
                return ((string)(this["contactsEndpoint"]));
            }
            set {
                this["contactsEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("healthcheck/")]
        public string healthcheckEndpoint {
            get {
                return ((string)(this["healthcheckEndpoint"]));
            }
            set {
                this["healthcheckEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("application.wadl/")]
        public string applicationEndpoint {
            get {
                return ((string)(this["applicationEndpoint"]));
            }
            set {
                this["applicationEndpoint"] = value;
            }
        }
    }
}
